# Generated by Django 4.2.8 on 2023-12-12 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=12)),
                ("mobile_operator_code", models.CharField(max_length=10)),
                ("tag", models.CharField(max_length=50)),
                ("timezone", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date_time", models.DateTimeField()),
                ("message_text", models.TextField()),
                ("client_filter_operator_code", models.CharField(max_length=10)),
                ("client_filter_tag", models.CharField(max_length=50)),
                ("end_date_time", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creation_date_time", models.DateTimeField()),
                ("send_status", models.CharField(max_length=50)),
                (
                    "client_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="nserv.client"
                    ),
                ),
                (
                    "newsletter_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nserv.newsletter",
                    ),
                ),
            ],
        ),
    ]
